# Generated by Django 5.1.6 on 2025-03-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
