# Generated by Django 5.1.6 on 2025-03-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('title', 'createdOn'), ('title', 'entry')},
        ),
    ]
