# Generated by Django 5.1.6 on 2025-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_rename_module_module_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-createdOn']},
        ),
        migrations.AddField(
            model_name='gallery',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
