# Generated by Django 5.1.6 on 2025-04-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_gallery_options_gallery_createdon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-createdOn'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('image', 'createdOn')},
        ),
    ]
