# Generated by Django 5.1.7 on 2025-05-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
